//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello 1.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string R_About {
            get {
                return ResourceManager.GetString("R_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2021.
        /// </summary>
        public static string R_About_Copyright {
            get {
                return ResourceManager.GetString("R_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Space(s).
        /// </summary>
        public static string R_AddSpaces {
            get {
                return ResourceManager.GetString("R_AddSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Suffix.
        /// </summary>
        public static string R_AlphaSuffix {
            get {
                return ResourceManager.GetString("R_AlphaSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is from App Strings.
        /// </summary>
        public static string R_AppStrings {
            get {
                return ResourceManager.GetString("R_AppStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Sheets.
        /// </summary>
        public static string R_AvailSheets {
            get {
                return ResourceManager.GetString("R_AvailSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_16.png.
        /// </summary>
        public static string R_ButtonImage16 {
            get {
                return ResourceManager.GetString("R_ButtonImage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_32.png.
        /// </summary>
        public static string R_ButtonImage32 {
            get {
                return ResourceManager.GetString("R_ButtonImage32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_1_Click_16.png.
        /// </summary>
        public static string R_ButtonImageOneClick16 {
            get {
                return ResourceManager.GetString("R_ButtonImageOneClick16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_1_Click_32.png.
        /// </summary>
        public static string R_ButtonImageOneClick32 {
            get {
                return ResourceManager.GetString("R_ButtonImageOneClick32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        public static string R_ButtonNameBott {
            get {
                return ResourceManager.GetString("R_ButtonNameBott", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shts 1-Click.
        /// </summary>
        public static string R_ButtonNameBottOneClick {
            get {
                return ResourceManager.GetString("R_ButtonNameBottOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string R_ButtonNameTop {
            get {
                return ResourceManager.GetString("R_ButtonNameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string R_ButtonNameTopCreate {
            get {
                return ResourceManager.GetString("R_ButtonNameTopCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string R_ButtonNameTopOneClick {
            get {
                return ResourceManager.GetString("R_ButtonNameTopOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string R_ButtonNameTopOneClickCreate {
            get {
                return ResourceManager.GetString("R_ButtonNameTopOneClickCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string R_Cancel {
            get {
                return ResourceManager.GetString("R_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot derive sheet name.
        /// </summary>
        public static string R_CannotNameSheet {
            get {
                return ResourceManager.GetString("R_CannotNameSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Character Entered.
        /// </summary>
        public static string R_CharacterInvalid {
            get {
                return ResourceManager.GetString("R_CharacterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters:.
        /// </summary>
        public static string R_CharactersInvalid {
            get {
                return ResourceManager.GetString("R_CharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string R_Close {
            get {
                return ResourceManager.GetString("R_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string R_Command {
            get {
                return ResourceManager.GetString("R_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command_1Click.
        /// </summary>
        public static string R_Command1Click {
            get {
                return ResourceManager.GetString("R_Command1Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sheets.
        /// </summary>
        public static string R_CommandDescCreate {
            get {
                return ResourceManager.GetString("R_CommandDescCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Create Sheets.
        /// </summary>
        public static string R_CommandDescOneClickCreate {
            get {
                return ResourceManager.GetString("R_CommandDescOneClickCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheets.
        /// </summary>
        public static string R_CommandDescription {
            get {
                return ResourceManager.GetString("R_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Duplicate Sheets.
        /// </summary>
        public static string R_CommandDescriptionOneClick {
            get {
                return ResourceManager.GetString("R_CommandDescriptionOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        public static string R_Copies {
            get {
                return ResourceManager.GetString("R_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string R_Copy {
            get {
                return ResourceManager.GetString("R_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty Sheets.
        /// </summary>
        public static string R_CreateSheets {
            get {
                return ResourceManager.GetString("R_CreateSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cyberstudioApps.com.
        /// </summary>
        public static string R_CyberStudioAddr {
            get {
                return ResourceManager.GetString("R_CyberStudioAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cyberstudio.pro/?page_id=654.
        /// </summary>
        public static string R_CyberStudioDupSheetsAddr {
            get {
                return ResourceManager.GetString("R_CyberStudioDupSheetsAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyberStudio Apps.
        /// </summary>
        public static string R_CyberStudioTitle {
            get {
                return ResourceManager.GetString("R_CyberStudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider Characters.
        /// </summary>
        public static string R_DivChars {
            get {
                return ResourceManager.GetString("R_DivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom: [?].
        /// </summary>
        public static string R_DivCustom {
            get {
                return ResourceManager.GetString("R_DivCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash:  -.
        /// </summary>
        public static string R_DivDash {
            get {
                return ResourceManager.GetString("R_DivDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string R_DivNone {
            get {
                return ResourceManager.GetString("R_DivNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:  ..
        /// </summary>
        public static string R_DivPeriod {
            get {
                return ResourceManager.GetString("R_DivPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space:  &apos; &apos;.
        /// </summary>
        public static string R_DivSpace {
            get {
                return ResourceManager.GetString("R_DivSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string R_Done {
            get {
                return ResourceManager.GetString("R_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet.
        /// </summary>
        public static string R_DupSheet {
            get {
                return ResourceManager.GetString("R_DupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet and Views.
        /// </summary>
        public static string R_DupSheetAndViews {
            get {
                return ResourceManager.GetString("R_DupSheetAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeff@cyberstudioapps.com.
        /// </summary>
        public static string R_EmailAddress {
            get {
                return ResourceManager.GetString("R_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Custom Divider Characters.
        /// </summary>
        public static string R_EnterDivChars {
            get {
                return ResourceManager.GetString("R_EnterDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Custom Suffix.
        /// </summary>
        public static string R_EnterSuffix {
            get {
                return ResourceManager.GetString("R_EnterSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious and unexpected error occurred and I cannot continue..
        /// </summary>
        public static string R_ErrCannotProceed {
            get {
                return ResourceManager.GetString("R_ErrCannotProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create the Sheet.
        /// </summary>
        public static string R_ErrCreateSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrCreateSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet failed 
        ///Reason: .
        /// </summary>
        public static string R_ErrDupSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrDupSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please email this information to:.
        /// </summary>
        public static string R_ErrEmailTo {
            get {
                return ResourceManager.GetString("R_ErrEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string R_ErrError {
            get {
                return ResourceManager.GetString("R_ErrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet Warning.
        /// </summary>
        public static string R_ErrMakeButtonFailDesc {
            get {
                return ResourceManager.GetString("R_ErrMakeButtonFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Add Button!.
        /// </summary>
        public static string R_ErrMakeButtonFailTitle {
            get {
                return ResourceManager.GetString("R_ErrMakeButtonFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model has no sheet so duplicate sheets cannot be made.  Please make at least one sheet and try again..
        /// </summary>
        public static string R_ErrNoSheetsContent {
            get {
                return ResourceManager.GetString("R_ErrNoSheetsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheets cannot continue.
        /// </summary>
        public static string R_ErrNoSheetsMainMsg_DupShts {
            get {
                return ResourceManager.GetString("R_ErrNoSheetsMainMsg_DupShts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click cannot continue.
        /// </summary>
        public static string R_ErrNoSheetsMainMsg_OneClick {
            get {
                return ResourceManager.GetString("R_ErrNoSheetsMainMsg_OneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Has No Sheets.
        /// </summary>
        public static string R_ErrNoSheetsTitle {
            get {
                return ResourceManager.GetString("R_ErrNoSheetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click is set to use a Template sheet but the template sheet does not exist:.
        /// </summary>
        public static string R_ErrNoTemplateContent {
            get {
                return ResourceManager.GetString("R_ErrNoTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Not Found.
        /// </summary>
        public static string R_ErrNoTemplateMain {
            get {
                return ResourceManager.GetString("R_ErrNoTemplateMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Sheet Does Not Exist.
        /// </summary>
        public static string R_ErrNoTemplateTitle {
            get {
                return ResourceManager.GetString("R_ErrNoTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Option is to use the current view as the basis for the new sheet&apos;s number and name. Since the current view is not a sheet view, I don&apos;t have a sheet number or name to use as the basis for the number and name of the new sheets.
        ///
        ///Please make a sheet view as the current view and select One Click again..
        /// </summary>
        public static string R_ErrNotViewSheetContent {
            get {
                return ResourceManager.GetString("R_ErrNotViewSheetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Active View is not a Sheet View.
        /// </summary>
        public static string R_ErrNotViewSheetMain {
            get {
                return ResourceManager.GetString("R_ErrNotViewSheetMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active View is not a Sheet View.
        /// </summary>
        public static string R_ErrNotViewSheetTitle {
            get {
                return ResourceManager.GetString("R_ErrNotViewSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click settings have not been configured and saved.  Please open the duplicate sheets dialog, configure your one click settings, and save the settings.
        /// </summary>
        public static string R_ErrOneClickSettingsMissingContent {
            get {
                return ResourceManager.GetString("R_ErrOneClickSettingsMissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Settings Have Not Been Saved.
        /// </summary>
        public static string R_ErrOneClickSettingsMissingMain {
            get {
                return ResourceManager.GetString("R_ErrOneClickSettingsMissingMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Settings Are Not Defined.
        /// </summary>
        public static string R_ErrOneClickSettingsMissingTitle {
            get {
                return ResourceManager.GetString("R_ErrOneClickSettingsMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sheet is not selected
        ///
        ///Please select a sheet to proceed.
        /// </summary>
        public static string R_ErrSelectSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrSelectSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to create a new sheet, an existing sheet
        ///must be selected.  Please select a sheet or select cancel..
        /// </summary>
        public static string R_ErrSelShtMainCont {
            get {
                return ResourceManager.GetString("R_ErrSelShtMainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sheet Must Be Selected.
        /// </summary>
        public static string R_ErrSelShtMainInst {
            get {
                return ResourceManager.GetString("R_ErrSelShtMainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Not Selected.
        /// </summary>
        public static string R_ErrSelShtTitle {
            get {
                return ResourceManager.GetString("R_ErrSelShtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string R_Example {
            get {
                return ResourceManager.GetString("R_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        public static string R_FormatSheetNumberUndef {
            get {
                return ResourceManager.GetString("R_FormatSheetNumberUndef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Current.
        /// </summary>
        public static string R_FromCurrent {
            get {
                return ResourceManager.GetString("R_FromCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Characters.
        /// </summary>
        public static string R_GroupChars {
            get {
                return ResourceManager.GetString("R_GroupChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will create new empty sheets using the title block indicated and using the &quot;New Sheet Options&quot;.
        ///
        ///To create new sheet:
        ///1.  Select &quot;Create New Sheets&quot; from the list of Operations
        ///2.  (Optional): Change the &quot;New Sheet Options&quot; (options are persistent)
        ///3.  (Optional): Indicate the number of copies (default is one, maximum is 99)
        ///4.  (Optional): Choose a title block to use for the new sheets.
        ///    or choose &lt;no titleblock&gt;
        ///
        ///Select cancel to not create the new sheets and exit.
        ///
        ///Select OK to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpCreateSheets {
            get {
                return ResourceManager.GetString("R_HelpCreateSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty Sheets.
        /// </summary>
        public static string R_HelpCreateSheetsTitle {
            get {
                return ResourceManager.GetString("R_HelpCreateSheetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will duplicate an existing sheet and all of the elements contained on the sheet other than single sheet elements.  That is, any element that can only occur once on a sheet (e.g. floor plan view) will not be copied - the other elements are copied to a location matching the original location.  Also, due to Revit® limitations, the viewport title will match the original but cannot be positioned to match the original. 
        ///
        ///If the current view is a sheet, that sheet is pre-selected as the sheet to be d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpDupSheet {
            get {
                return ResourceManager.GetString("R_HelpDupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will duplicate an existing sheet and all of the elements and views, even those restricted to placement on a single sheet, with detailing.  Also, due to Revit® limitations, the viewport title will match the original but cannot be positioned to match the original.
        ///
        ///If the current view is a sheet, the sheet is pre-selected as the sheet to be duplicated.
        ///
        ///To duplicate a sheet and views:
        ///1.  (Optional): Open a sheet view
        ///2.  Select &quot;Duplicate Sheet and Views&quot; from the list of Operations
        ///3.  (O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpDupSheetAndViews {
            get {
                return ResourceManager.GetString("R_HelpDupSheetAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet and Views.
        /// </summary>
        public static string R_HelpDupSheetAndViewsTitle {
            get {
                return ResourceManager.GetString("R_HelpDupSheetAndViewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet.
        /// </summary>
        public static string R_HelpDupSheetTitle {
            get {
                return ResourceManager.GetString("R_HelpDupSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the &quot;From Current&quot; option, the names for new sheets and new views are based on the current sheet number and sheet name..
        /// </summary>
        public static string R_HelpFromCurr {
            get {
                return ResourceManager.GetString("R_HelpFromCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings determine how the current sheet name is adjusted to derive thew new sheet name.  The new sheet number is a combination of the current sheet name plus an optional divider and an optional suffix.  Note that if the &apos;none&apos; suffix is chosen, then a divider is also not used.  These settings persist between usages and sessions.
        ///The divider character may be nothing, a preset character (a space, a period, or a dash), or a custom character.
        ///The suffix must be one of the following:
        ///- The phrase &apos;Copy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpFromCurrNameFmt {
            get {
                return ResourceManager.GetString("R_HelpFromCurrNameFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Current Name Format.
        /// </summary>
        public static string R_HelpFromCurrNameFmtTitle {
            get {
                return ResourceManager.GetString("R_HelpFromCurrNameFmtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings determine how the current sheet number is adjusted to derive the new sheet number.  The new sheet number is a combination of the current sheet number plus an optional divider character plus a required suffix.  These settings persist between usages and sessions.
        ///The divider character may be nothing, a preset character (a space, a period, or a dash), or a custom character.
        ///The suffix must be one of the following:
        ///- A sequential number with one of four formats (minimum number of zero filled d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpFromCurrNumFmt {
            get {
                return ResourceManager.GetString("R_HelpFromCurrNumFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Current Number Format.
        /// </summary>
        public static string R_HelpFromCurrNumFmtTitle {
            get {
                return ResourceManager.GetString("R_HelpFromCurrNumFmtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Current.
        /// </summary>
        public static string R_HelpFromCurrTitle {
            get {
                return ResourceManager.GetString("R_HelpFromCurrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the &quot;Per Settings&quot; option, the names for new sheets and new views are based on the settings in this section..
        /// </summary>
        public static string R_HelpPerSetg {
            get {
                return ResourceManager.GetString("R_HelpPerSetg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings determine the new sheet name.  The new sheet name the &quot;Sheet Name&quot; provided.  If the &quot;Increment Sheet Name&quot; check box is selected, each sheet name is followed by a sequential number starting with the &quot;Sequence #&quot; value except the actual sequential number will match the sequential number used for the sheet number.
        ///These settings persist between usages and sessions..
        /// </summary>
        public static string R_HelpPerSetgNameFmt {
            get {
                return ResourceManager.GetString("R_HelpPerSetgNameFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Settings Name Format.
        /// </summary>
        public static string R_HelpPerSetgNameFmtTitle {
            get {
                return ResourceManager.GetString("R_HelpPerSetgNameFmtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings determine the new sheet number.  The new sheet number is combination of the &quot;Number Prefix&quot; and a sequential number.  The format for the sequential number, that is minimum number of digits (zero filled), is determined by the number format drop down.  The sequential number start with the &quot;Sequence #&quot; provided in the &quot;New Sheet Name Format&quot; section below except the actual sheet number will be the first available, since duplicate sheet numbers are not allowed.
        ///These settings persist between usa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpPerSetgNumFmt {
            get {
                return ResourceManager.GetString("R_HelpPerSetgNumFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Settings Number Format.
        /// </summary>
        public static string R_HelpPerSetgNumFmtTitle {
            get {
                return ResourceManager.GetString("R_HelpPerSetgNumFmtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Settings.
        /// </summary>
        public static string R_HelpPerSetgTitle {
            get {
                return ResourceManager.GetString("R_HelpPerSetgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more new sheets will be created based on your options and settings.
        /// </summary>
        public static string R_HelpProceed {
            get {
                return ResourceManager.GetString("R_HelpProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed Button.
        /// </summary>
        public static string R_HelpProceedTitle {
            get {
                return ResourceManager.GetString("R_HelpProceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your One Click options and settings will be restored.  The current options and settings will be saved and can be restored using the Restore Settings button..
        /// </summary>
        public static string R_HelpRestoreOneClick {
            get {
                return ResourceManager.GetString("R_HelpRestoreOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore One Click Button.
        /// </summary>
        public static string R_HelpRestoreOneClickTitle {
            get {
                return ResourceManager.GetString("R_HelpRestoreOneClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current options and settings will be saved as your One Click settings.
        ///One click, which also has a separate button on the ribbon, can be used to quickly create a sheet.  One-click can use a preconfigured template sheet and options to quickly create new duplicate sheets.  The one-click settings are saved and are available between sessions and between models (this is a per machine setting so the one-click settings from one model is available in a different model).  
        ///Since this is a per machine setting,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpSaveAsOneClick {
            get {
                return ResourceManager.GetString("R_HelpSaveAsOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As One Click Button.
        /// </summary>
        public static string R_HelpSaveAsOneClickTitle {
            get {
                return ResourceManager.GetString("R_HelpSaveAsOneClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the options and settings saved when the Restore One Click button was pressed..
        /// </summary>
        public static string R_HelpSavedRestore {
            get {
                return ResourceManager.GetString("R_HelpSavedRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Settings Button.
        /// </summary>
        public static string R_HelpSavedRestoreTitle {
            get {
                return ResourceManager.GetString("R_HelpSavedRestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Message.
        /// </summary>
        public static string R_HelpTitle {
            get {
                return ResourceManager.GetString("R_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tells One Click to use this sheet as the template for duplicating sheets.  That is, duplicate sheets will be based on this sheet.  Note, however, that what is duplicated is determined by the Operation setting.
        /// </summary>
        public static string R_HelpUseAsTemplate {
            get {
                return ResourceManager.GetString("R_HelpUseAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use sheet as a Template.
        /// </summary>
        public static string R_HelpUseAsTemplateTitle {
            get {
                return ResourceManager.GetString("R_HelpUseAsTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting determines whether the parameters, standard and custom, for the selected sheet will be applied to the new sheet.
        ///This setting persists between usages and sessions.  .
        /// </summary>
        public static string R_HelpUseParams {
            get {
                return ResourceManager.GetString("R_HelpUseParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse exiting parameters.
        /// </summary>
        public static string R_HelpUseParamsTitle {
            get {
                return ResourceManager.GetString("R_HelpUseParamsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting determines which title block will be used for the new sheets.  The choices are:
        ///&lt;No titleblock&gt; = no title block will be added to the new sheet.
        ///&lt;From Selected Sheet&gt; = the title block of the selected sheet will be used for the new sheets.
        ///or from one of the other titleblocks loaded into the model.
        ///This setting persists between usages and sessions..
        /// </summary>
        public static string R_HelpUseThisTblk {
            get {
                return ResourceManager.GetString("R_HelpUseThisTblk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this title block.
        /// </summary>
        public static string R_HelpUseThisTblkTitle {
            get {
                return ResourceManager.GetString("R_HelpUseThisTblkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Sheet Name.
        /// </summary>
        public static string R_IncSheetName {
            get {
                return ResourceManager.GetString("R_IncSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string R_Make {
            get {
                return ResourceManager.GetString("R_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string R_NamespacePrefixSubject {
            get {
                return ResourceManager.GetString("R_NamespacePrefixSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet.
        /// </summary>
        public static string R_NewSheetPrefix {
            get {
                return ResourceManager.GetString("R_NewSheetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider Chars.
        /// </summary>
        public static string R_NewShtFmtTitleDivChars {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string R_NewShtFmtTitleOrig {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string R_NewShtFmtTitleSuffix {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Name Format.
        /// </summary>
        public static string R_NewShtNameFormat {
            get {
                return ResourceManager.GetString("R_NewShtNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Number Format.
        /// </summary>
        public static string R_NewShtNumFormat {
            get {
                return ResourceManager.GetString("R_NewShtNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Added Characters.
        /// </summary>
        public static string R_None {
            get {
                return ResourceManager.GetString("R_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Suffix.
        /// </summary>
        public static string R_NoSuffix {
            get {
                return ResourceManager.GetString("R_NoSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Suffix.
        /// </summary>
        public static string R_NumericSuffix {
            get {
                return ResourceManager.GetString("R_NumericSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Format.
        /// </summary>
        public static string R_NumFmt {
            get {
                return ResourceManager.GetString("R_NumFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Prefix.
        /// </summary>
        public static string R_NumPrefix {
            get {
                return ResourceManager.GetString("R_NumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string R_Ok {
            get {
                return ResourceManager.GetString("R_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore 
        ///One Click.
        /// </summary>
        public static string R_OneClickRestore {
            get {
                return ResourceManager.GetString("R_OneClickRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Restored.
        /// </summary>
        public static string R_OneClickRestored {
            get {
                return ResourceManager.GetString("R_OneClickRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As 
        ///One Click.
        /// </summary>
        public static string R_OneClickSave {
            get {
                return ResourceManager.GetString("R_OneClickSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Saved.
        /// </summary>
        public static string R_OneClickSaved {
            get {
                return ResourceManager.GetString("R_OneClickSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string R_Operation {
            get {
                return ResourceManager.GetString("R_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Options.
        /// </summary>
        public static string R_OpOptions {
            get {
                return ResourceManager.GetString("R_OpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Suffix.
        /// </summary>
        public static string R_OtherSuffix {
            get {
                return ResourceManager.GetString("R_OtherSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Settings.
        /// </summary>
        public static string R_PerSettings {
            get {
                return ResourceManager.GetString("R_PerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string R_Proceed {
            get {
                return ResourceManager.GetString("R_Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Plan.
        /// </summary>
        public static string R_Sample {
            get {
                return ResourceManager.GetString("R_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore
        ///Settings.
        /// </summary>
        public static string R_SavedRestore {
            get {
                return ResourceManager.GetString("R_SavedRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation / Grouping Characters.
        /// </summary>
        public static string R_SepGroup {
            get {
                return ResourceManager.GetString("R_SepGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string R_SheetName {
            get {
                return ResourceManager.GetString("R_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        public static string R_SheetNum {
            get {
                return ResourceManager.GetString("R_SheetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Options.
        /// </summary>
        public static string R_SheetOpts {
            get {
                return ResourceManager.GetString("R_SheetOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string R_ShtOpCurExample {
            get {
                return ResourceManager.GetString("R_ShtOpCurExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example based on selected sheet.
        /// </summary>
        public static string R_ShtOpCurExampleDesc {
            get {
                return ResourceManager.GetString("R_ShtOpCurExampleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current
        ///Sheet Name.
        /// </summary>
        public static string R_ShtOpCurOrigShtName {
            get {
                return ResourceManager.GetString("R_ShtOpCurOrigShtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current
        ///Sheet Number.
        /// </summary>
        public static string R_ShtOpCurOrigShtNum {
            get {
                return ResourceManager.GetString("R_ShtOpCurOrigShtNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string R_ShtOpCurSample {
            get {
                return ResourceManager.GetString("R_ShtOpCurSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence #.
        /// </summary>
        public static string R_ShtOpCurSampleSequence {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sheet Name.
        /// </summary>
        public static string R_ShtOpCurSampleShtName {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleShtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A01.01-00.
        /// </summary>
        public static string R_ShtOpCurSampleShtNum {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleShtNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        public static string R_ShtOpSetCkBx {
            get {
                return ResourceManager.GetString("R_ShtOpSetCkBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .X-.
        /// </summary>
        public static string R_ShtOpSetNumPrefix {
            get {
                return ResourceManager.GetString("R_ShtOpSetNumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a | b | ... | ab | etc.
        /// </summary>
        public static string R_SuffixNameAlphaLc {
            get {
                return ResourceManager.GetString("R_SuffixNameAlphaLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A | B | ... | AB | etc.
        /// </summary>
        public static string R_SuffixNameAlphaUc {
            get {
                return ResourceManager.GetString("R_SuffixNameAlphaUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy 1 | Copy 2 | etc.
        /// </summary>
        public static string R_SuffixNameCopy1 {
            get {
                return ResourceManager.GetString("R_SuffixNameCopy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy A | Copy B | etc.
        /// </summary>
        public static string R_SuffixNameCopyA {
            get {
                return ResourceManager.GetString("R_SuffixNameCopyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom: [?].
        /// </summary>
        public static string R_SuffixNameCustom {
            get {
                return ResourceManager.GetString("R_SuffixNameCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string R_SuffixNameNone {
            get {
                return ResourceManager.GetString("R_SuffixNameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 | 2 | ... | etc.
        /// </summary>
        public static string R_SuffixNameNumeric {
            get {
                return ResourceManager.GetString("R_SuffixNameNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a | b | ... | ab | etc.
        /// </summary>
        public static string R_SuffixNumAlphaLc {
            get {
                return ResourceManager.GetString("R_SuffixNumAlphaLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A | B | ... | AB | etc.
        /// </summary>
        public static string R_SuffixNumAlphaUc {
            get {
                return ResourceManager.GetString("R_SuffixNumAlphaUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string R_SuffixNumNumeric1 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        public static string R_SuffixNumNumeric2 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        public static string R_SuffixNumNumeric3 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        public static string R_SuffixNumNumeric4 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000.
        /// </summary>
        public static string R_SuffixNumNumeric5 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;From Selected Sheet&gt;.
        /// </summary>
        public static string R_TBlkFromSelSheet {
            get {
                return ResourceManager.GetString("R_TBlkFromSelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no titleblock&gt;.
        /// </summary>
        public static string R_TBlkNone {
            get {
                return ResourceManager.GetString("R_TBlkNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Files.
        /// </summary>
        public static string R_Trace_File_Count {
            get {
                return ResourceManager.GetString("R_Trace_File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string R_Trace_FileName {
            get {
                return ResourceManager.GetString("R_Trace_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have gotten here due to some unforeseen issue with the software.  This dialog box will allow the collection of detailed information about what is happening so I may analyze and, hopefully, resolve the issue.
        /// 
        ///To use, please press the Start Trace button and go through the normal steps that is causing the problem.  If the app crashes, the data is automatically saved to a Log File otherwise, press the Stop Trace button.  The log file can then be emailed to me.  
        /// 
        ///I ask you email the file so you may l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_Trace_Help {
            get {
                return ResourceManager.GetString("R_Trace_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        public static string R_Trace_HelpTitle {
            get {
                return ResourceManager.GetString("R_Trace_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Trace
        ///File.
        /// </summary>
        public static string R_Trace_Show {
            get {
                return ResourceManager.GetString("R_Trace_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Trace
        ///Folder.
        /// </summary>
        public static string R_Trace_Show_Folder {
            get {
                return ResourceManager.GetString("R_Trace_Show_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Trace.
        /// </summary>
        public static string R_Trace_Start {
            get {
                return ResourceManager.GetString("R_Trace_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Status.
        /// </summary>
        public static string R_Trace_Status {
            get {
                return ResourceManager.GetString("R_Trace_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        public static string R_Trace_Status_Active {
            get {
                return ResourceManager.GetString("R_Trace_Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Status.
        /// </summary>
        public static string R_Trace_Status_Process {
            get {
                return ResourceManager.GetString("R_Trace_Status_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Trace.
        /// </summary>
        public static string R_Trace_Stop {
            get {
                return ResourceManager.GetString("R_Trace_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the trace dialog box
        ///used to help diagnose program problems.
        /// </summary>
        public static string R_Trace_ToolTip {
            get {
                return ResourceManager.GetString("R_Trace_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        public static string R_UiPanelName {
            get {
                return ResourceManager.GetString("R_UiPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Used.
        /// </summary>
        public static string R_UiTabName {
            get {
                return ResourceManager.GetString("R_UiTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this sheet as a One Click Template.
        /// </summary>
        public static string R_UseSheetForOneClick {
            get {
                return ResourceManager.GetString("R_UseSheetForOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse parameters from existing sheet.
        /// </summary>
        public static string R_UseSheetParameters {
            get {
                return ResourceManager.GetString("R_UseSheetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Title Block for new sheets.
        /// </summary>
        public static string R_UseThisTtlBlk {
            get {
                return ResourceManager.GetString("R_UseThisTtlBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New View Name Options.
        /// </summary>
        public static string R_ViewOpts {
            get {
                return ResourceManager.GetString("R_ViewOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Divider Characters.
        /// </summary>
        public static string R_WindowTitleDivChars {
            get {
                return ResourceManager.GetString("R_WindowTitleDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string R_WindowTitleErrorReport {
            get {
                return ResourceManager.GetString("R_WindowTitleErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheets.
        /// </summary>
        public static string R_WindowTitleSelView {
            get {
                return ResourceManager.GetString("R_WindowTitleSelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sheets.
        /// </summary>
        public static string R_WindowTitleSelViewCreate {
            get {
                return ResourceManager.GetString("R_WindowTitleSelViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Suffix.
        /// </summary>
        public static string R_WindowTitleSuffix {
            get {
                return ResourceManager.GetString("R_WindowTitleSuffix", resourceCulture);
            }
        }
    }
}
