//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello 1.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string R_About {
            get {
                return ResourceManager.GetString("R_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Space(s).
        /// </summary>
        public static string R_AddSpaces {
            get {
                return ResourceManager.GetString("R_AddSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Suffix.
        /// </summary>
        public static string R_AlphaSuffix {
            get {
                return ResourceManager.GetString("R_AlphaSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is from App Strings.
        /// </summary>
        public static string R_AppStrings {
            get {
                return ResourceManager.GetString("R_AppStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Sheets.
        /// </summary>
        public static string R_AvailSheets {
            get {
                return ResourceManager.GetString("R_AvailSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_16.png.
        /// </summary>
        public static string R_ButtonImage16 {
            get {
                return ResourceManager.GetString("R_ButtonImage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSheets_32.png.
        /// </summary>
        public static string R_ButtonImage32 {
            get {
                return ResourceManager.GetString("R_ButtonImage32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        public static string R_ButtonNameBott {
            get {
                return ResourceManager.GetString("R_ButtonNameBott", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string R_ButtonNameTop {
            get {
                return ResourceManager.GetString("R_ButtonNameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string R_Cancel {
            get {
                return ResourceManager.GetString("R_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot derive sheet name.
        /// </summary>
        public static string R_CannotNameSheet {
            get {
                return ResourceManager.GetString("R_CannotNameSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Character Entered.
        /// </summary>
        public static string R_CharacterInvalid {
            get {
                return ResourceManager.GetString("R_CharacterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters:.
        /// </summary>
        public static string R_CharactersInvalid {
            get {
                return ResourceManager.GetString("R_CharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string R_Close {
            get {
                return ResourceManager.GetString("R_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string R_Command {
            get {
                return ResourceManager.GetString("R_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Existing Sheet.
        /// </summary>
        public static string R_CommandDescription {
            get {
                return ResourceManager.GetString("R_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        public static string R_Copies {
            get {
                return ResourceManager.GetString("R_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string R_Copy {
            get {
                return ResourceManager.GetString("R_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty Sheets.
        /// </summary>
        public static string R_CreateSheet {
            get {
                return ResourceManager.GetString("R_CreateSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider Characters.
        /// </summary>
        public static string R_DivChars {
            get {
                return ResourceManager.GetString("R_DivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom: [?].
        /// </summary>
        public static string R_DivCustom {
            get {
                return ResourceManager.GetString("R_DivCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash:  -.
        /// </summary>
        public static string R_DivDash {
            get {
                return ResourceManager.GetString("R_DivDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string R_DivNone {
            get {
                return ResourceManager.GetString("R_DivNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:  ..
        /// </summary>
        public static string R_DivPeriod {
            get {
                return ResourceManager.GetString("R_DivPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space:  &apos; &apos;.
        /// </summary>
        public static string R_DivSpace {
            get {
                return ResourceManager.GetString("R_DivSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet.
        /// </summary>
        public static string R_DupSheet {
            get {
                return ResourceManager.GetString("R_DupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet and Views.
        /// </summary>
        public static string R_DupSheetAndViews {
            get {
                return ResourceManager.GetString("R_DupSheetAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeff@cyberstudioapps.com.
        /// </summary>
        public static string R_EmailAddress {
            get {
                return ResourceManager.GetString("R_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider Characters.
        /// </summary>
        public static string R_EnterDivChars {
            get {
                return ResourceManager.GetString("R_EnterDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string R_EnterSuffix {
            get {
                return ResourceManager.GetString("R_EnterSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious and unexpected error occurred and I cannot continue..
        /// </summary>
        public static string R_ErrCannotProceed {
            get {
                return ResourceManager.GetString("R_ErrCannotProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create the Sheet.
        /// </summary>
        public static string R_ErrCreateSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrCreateSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet failed\nReason: .
        /// </summary>
        public static string R_ErrDupSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrDupSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please email this information to:.
        /// </summary>
        public static string R_ErrEmailTo {
            get {
                return ResourceManager.GetString("R_ErrEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string R_ErrError {
            get {
                return ResourceManager.GetString("R_ErrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheet Warning.
        /// </summary>
        public static string R_ErrMakeButtonFailDesc {
            get {
                return ResourceManager.GetString("R_ErrMakeButtonFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Add Button!.
        /// </summary>
        public static string R_ErrMakeButtonFailTitle {
            get {
                return ResourceManager.GetString("R_ErrMakeButtonFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sheet is not selected\n\nPlease select a sheet to proceed.
        /// </summary>
        public static string R_ErrSelectSheetFailDesc {
            get {
                return ResourceManager.GetString("R_ErrSelectSheetFailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to create a new sheet, an existing sheet\nmust be selected.  Please select a sheet or select cancel..
        /// </summary>
        public static string R_ErrSelShtMainCont {
            get {
                return ResourceManager.GetString("R_ErrSelShtMainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sheet Must Be Selected.
        /// </summary>
        public static string R_ErrSelShtMainInst {
            get {
                return ResourceManager.GetString("R_ErrSelShtMainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string R_Example {
            get {
                return ResourceManager.GetString("R_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        public static string R_FormatSheetNumberUndef {
            get {
                return ResourceManager.GetString("R_FormatSheetNumberUndef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Current.
        /// </summary>
        public static string R_FromCurrent {
            get {
                return ResourceManager.GetString("R_FromCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Characters.
        /// </summary>
        public static string R_GroupChars {
            get {
                return ResourceManager.GetString("R_GroupChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will create new empty sheets using the title block indicated and using the &quot;New Sheet Options&quot;.
        ///
        ///To create new sheet:
        ///1.  Select &quot;Create New Sheets&quot; from the list of Operations
        ///2.  (Optional): Change the &quot;New Sheet Options&quot;
        ///3.  (Optional): Indicate the number of copies (maximum is 99)
        ///4.  (Optional): Choose a title block to use for the new sheets.
        ///    or choose &lt;no titleblock&gt;
        ///
        ///Select OK to create the new sheets.
        ///Select cancel to not create the new sheets and exit.
        ///
        ///The a new sheet i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpCreateSheets {
            get {
                return ResourceManager.GetString("R_HelpCreateSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will duplicate an existing sheet and all of the elements contained on the sheet, within the limitations set by Revit®.  That is, any element that can only occur once on a sheet (e.g. floor plan view) will not be copied - the other elements are copied to a location matching the orignial location.  Also, due to Revit® limitations, the viewport title will match the orignial but cannot be positioned to match the original. 
        ///
        ///If the current view is a sheet, the sheet is pre-selected as the sheet to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpDuplicateSheet {
            get {
                return ResourceManager.GetString("R_HelpDuplicateSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is identical to the &quot;Duplicate Sheet&quot; option except that views restricted to placement on a single sheet will be copied, with detailing, and the view copy will be placed on the newly duplicated sheet.  Again, due to Revit® limitations, the viewport title will match the orignial but cannot be positioned to match the original.
        ///
        ///If the current view is a sheet, the sheet is pre-selected as the sheet to be duplicated.
        ///
        ///To duplicate a sheet and views:
        ///1.  (Optional): Open a sheet view
        ///2.  Select [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R_HelpDuplicateSheetAndViews {
            get {
                return ResourceManager.GetString("R_HelpDuplicateSheetAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Sheet Name.
        /// </summary>
        public static string R_IncSheetName {
            get {
                return ResourceManager.GetString("R_IncSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string R_Make {
            get {
                return ResourceManager.GetString("R_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string R_NamespacePrefixSubject {
            get {
                return ResourceManager.GetString("R_NamespacePrefixSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet.
        /// </summary>
        public static string R_NewSheetPrefix {
            get {
                return ResourceManager.GetString("R_NewSheetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider Chars.
        /// </summary>
        public static string R_NewShtFmtTitleDivChars {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string R_NewShtFmtTitleOrig {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string R_NewShtFmtTitleSuffix {
            get {
                return ResourceManager.GetString("R_NewShtFmtTitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Name Format.
        /// </summary>
        public static string R_NewShtNameFormat {
            get {
                return ResourceManager.GetString("R_NewShtNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Number Format.
        /// </summary>
        public static string R_NewShtNumFormat {
            get {
                return ResourceManager.GetString("R_NewShtNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Added Characters.
        /// </summary>
        public static string R_None {
            get {
                return ResourceManager.GetString("R_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Suffix.
        /// </summary>
        public static string R_NoSuffix {
            get {
                return ResourceManager.GetString("R_NoSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Suffix.
        /// </summary>
        public static string R_NumericSuffix {
            get {
                return ResourceManager.GetString("R_NumericSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Format.
        /// </summary>
        public static string R_NumFmt {
            get {
                return ResourceManager.GetString("R_NumFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Prefix.
        /// </summary>
        public static string R_NumPrefix {
            get {
                return ResourceManager.GetString("R_NumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string R_Ok {
            get {
                return ResourceManager.GetString("R_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore 
        ///One Click.
        /// </summary>
        public static string R_OneClickRestore {
            get {
                return ResourceManager.GetString("R_OneClickRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As 
        ///One Click.
        /// </summary>
        public static string R_OneClickSave {
            get {
                return ResourceManager.GetString("R_OneClickSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string R_Operation {
            get {
                return ResourceManager.GetString("R_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Options.
        /// </summary>
        public static string R_OpOptions {
            get {
                return ResourceManager.GetString("R_OpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Suffix.
        /// </summary>
        public static string R_OtherSuffix {
            get {
                return ResourceManager.GetString("R_OtherSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Settings.
        /// </summary>
        public static string R_PerSettings {
            get {
                return ResourceManager.GetString("R_PerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string R_Proceed {
            get {
                return ResourceManager.GetString("R_Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Plan.
        /// </summary>
        public static string R_Sample {
            get {
                return ResourceManager.GetString("R_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Saved
        ///Settings.
        /// </summary>
        public static string R_SavedRestore {
            get {
                return ResourceManager.GetString("R_SavedRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation / Grouping Characters.
        /// </summary>
        public static string R_SepGroup {
            get {
                return ResourceManager.GetString("R_SepGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string R_SheetName {
            get {
                return ResourceManager.GetString("R_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        public static string R_SheetNum {
            get {
                return ResourceManager.GetString("R_SheetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Options.
        /// </summary>
        public static string R_SheetOpts {
            get {
                return ResourceManager.GetString("R_SheetOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string R_ShtOpCurExample {
            get {
                return ResourceManager.GetString("R_ShtOpCurExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current
        ///Sheet Name.
        /// </summary>
        public static string R_ShtOpCurOrigShtName {
            get {
                return ResourceManager.GetString("R_ShtOpCurOrigShtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current
        ///Sheet Number.
        /// </summary>
        public static string R_ShtOpCurOrigShtNum {
            get {
                return ResourceManager.GetString("R_ShtOpCurOrigShtNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string R_ShtOpCurSample {
            get {
                return ResourceManager.GetString("R_ShtOpCurSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence #.
        /// </summary>
        public static string R_ShtOpCurSampleSequence {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sheet Name.
        /// </summary>
        public static string R_ShtOpCurSampleShtName {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleShtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A01.01-00.
        /// </summary>
        public static string R_ShtOpCurSampleShtNum {
            get {
                return ResourceManager.GetString("R_ShtOpCurSampleShtNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        public static string R_ShtOpSetCkBx {
            get {
                return ResourceManager.GetString("R_ShtOpSetCkBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .X-.
        /// </summary>
        public static string R_ShtOpSetNumPrefix {
            get {
                return ResourceManager.GetString("R_ShtOpSetNumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a | b | ... | ab | etc.
        /// </summary>
        public static string R_SuffixNameAlphaLc {
            get {
                return ResourceManager.GetString("R_SuffixNameAlphaLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A | B | ... | AB | etc.
        /// </summary>
        public static string R_SuffixNameAlphaUc {
            get {
                return ResourceManager.GetString("R_SuffixNameAlphaUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy 1 | Copy 2 | etc.
        /// </summary>
        public static string R_SuffixNameCopy1 {
            get {
                return ResourceManager.GetString("R_SuffixNameCopy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy A | Copy B | etc.
        /// </summary>
        public static string R_SuffixNameCopyA {
            get {
                return ResourceManager.GetString("R_SuffixNameCopyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom: [?].
        /// </summary>
        public static string R_SuffixNameCustom {
            get {
                return ResourceManager.GetString("R_SuffixNameCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string R_SuffixNameNone {
            get {
                return ResourceManager.GetString("R_SuffixNameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 | 2 | ... | etc.
        /// </summary>
        public static string R_SuffixNameNumeric {
            get {
                return ResourceManager.GetString("R_SuffixNameNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a | b | ... | ab | etc.
        /// </summary>
        public static string R_SuffixNumAlphaLc {
            get {
                return ResourceManager.GetString("R_SuffixNumAlphaLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A | B | ... | AB | etc.
        /// </summary>
        public static string R_SuffixNumAlphaUc {
            get {
                return ResourceManager.GetString("R_SuffixNumAlphaUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string R_SuffixNumNumeric1 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        public static string R_SuffixNumNumeric2 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        public static string R_SuffixNumNumeric3 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        public static string R_SuffixNumNumeric4 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000.
        /// </summary>
        public static string R_SuffixNumNumeric5 {
            get {
                return ResourceManager.GetString("R_SuffixNumNumeric5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;From Selected Sheet&gt;.
        /// </summary>
        public static string R_TBlkFromSelSheet {
            get {
                return ResourceManager.GetString("R_TBlkFromSelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no titleblock&gt;.
        /// </summary>
        public static string R_TBlkNone {
            get {
                return ResourceManager.GetString("R_TBlkNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string R_UiPanelName {
            get {
                return ResourceManager.GetString("R_UiPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Used.
        /// </summary>
        public static string R_UiTabName {
            get {
                return ResourceManager.GetString("R_UiTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use parameters from existing sheet.
        /// </summary>
        public static string R_UseSheetParameters {
            get {
                return ResourceManager.GetString("R_UseSheetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Title Block for new sheets.
        /// </summary>
        public static string R_UseThisTtlBlk {
            get {
                return ResourceManager.GetString("R_UseThisTtlBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New View Name Options.
        /// </summary>
        public static string R_ViewOpts {
            get {
                return ResourceManager.GetString("R_ViewOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Divider Characters.
        /// </summary>
        public static string R_WindowTitleDivChars {
            get {
                return ResourceManager.GetString("R_WindowTitleDivChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string R_WindowTitleErrorReport {
            get {
                return ResourceManager.GetString("R_WindowTitleErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sheets.
        /// </summary>
        public static string R_WindowTitleSelView {
            get {
                return ResourceManager.GetString("R_WindowTitleSelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Suffix.
        /// </summary>
        public static string R_WindowTitleSuffix {
            get {
                return ResourceManager.GetString("R_WindowTitleSuffix", resourceCulture);
            }
        }
    }
}
